Remove snapshot from friclone-pull. Let the users create the snapshots themselves.

diff --git a/friclone-pull b/friclone-pull
--- a/friclone-pull
+++ b/friclone-pull
@@ -15,9 +15,9 @@ fi
 SUBVOL="$1"
 shift
 
-if ! ssh $* friclone snapshot "${SUBVOL}"; then
-    echo "friclone snapshot ${SUBVOL} failed!"
-fi
+#if ! ssh $* friclone snapshot "${SUBVOL}"; then
+#    echo "friclone snapshot ${SUBVOL} failed!"
+#fi
 
 if ! SNAPTAB=$(ssh $* friclone send "${SUBVOL}" latest); then
     SNAPTAB=""
